//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.07.18 at 10:32:30 AM EEST
//


package com.seeburger.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeeList }
     *
     */
    public EmployeeList createEmployeeList() {
        return new EmployeeList();
    }

    /**
     * Create an instance of {@link EmployeeList.Employee }
     *
     */
    public EmployeeList.Employee createEmployeeListEmployee() {
        return new EmployeeList.Employee();
    }

    /**
     * Create an instance of {@link EmployeeList.Employee.ExitDateList }
     *
     */
    public EmployeeList.Employee.ExitDateList createEmployeeListEmployeeExitDateList() {
        return new EmployeeList.Employee.ExitDateList();
    }

    /**
     * Create an instance of {@link EmployeeList.Employee.EnterDateList }
     *
     */
    public EmployeeList.Employee.EnterDateList createEmployeeListEmployeeEnterDateList() {
        return new EmployeeList.Employee.EnterDateList();
    }

    /**
     * Create an instance of {@link EmployeeList.Employee.EmployeeInfo }
     *
     */
    public EmployeeList.Employee.EmployeeInfo createEmployeeListEmployeeEmployeeInfo() {
        return new EmployeeList.Employee.EmployeeInfo();
    }

    /**
     * Create an instance of {@link EmployeeList.Employee.ExitDateList.Exit }
     *
     */
    public EmployeeList.Employee.ExitDateList.Exit createEmployeeListEmployeeExitDateListExit() {
        return new EmployeeList.Employee.ExitDateList.Exit();
    }

    /**
     * Create an instance of {@link EmployeeList.Employee.EnterDateList.Enter }
     *
     */
    public EmployeeList.Employee.EnterDateList.Enter createEmployeeListEmployeeEnterDateListEnter() {
        return new EmployeeList.Employee.EnterDateList.Enter();
    }

}
